export { authService } from "./auth.service.js";
export { serieService } from "./serie.service.js";
export { nivelEnsinoService } from "./nivel-ensino.service.js";
export { etapaService } from "./etapa.service.js";
export { tipoEducacaoService } from "./tipo-educacao.service.js";
export { escolaService } from "./escola.service.js";
export { turmaService } from "./turma.service.js";
export { matriculaService } from "./matricula.service.js";
export { documentoMatriculaService } from "./documento-matricula.service.js";
export { profissionalService } from "./profissional.service.js";
export { moduleService } from "./module.service.js";
export { phaseService } from "./phase.service.js";
export { calendarioService } from "./calendario.service.js";
// Módulo 2 — Gestão Pedagógica
export { frequenciaService } from "./frequencia.service.js";
export { notaService } from "./nota.service.js";
export { avaliacaoService } from "./avaliacao.service.js";
export { disciplinaService } from "./disciplina.service.js";
export { configuracaoAvaliacaoService } from "./configuracao-avaliacao.service.js";
export { gradeHorariaService } from "./grade-horaria.service.js";
// Módulo 4 — RH
export { pontoService } from "./ponto.service.js";
export { licencaService } from "./licenca.service.js";
// Módulo 3 — Portais por papel
export { portalService } from "./portal.service.js";
// Módulo 6 — Alimentação Escolar
export { cardapioService } from "./cardapio.service.js";
export { estoqueService } from "./estoque.service.js";
export { refeicaoService } from "./refeicao.service.js";
// Módulo 7 — Transporte Escolar
export { veiculoService } from "./veiculo.service.js";
export { motoristaService } from "./motorista.service.js";
export { rotaTransporteService } from "./rota-transporte.service.js";
export { manutencaoService } from "./manutencao.service.js";
// Módulo 8 — Gestão Democrática
export { colegiadoService } from "./colegiado.service.js";
export { gremioService } from "./gremio.service.js";
export { liderTurmaService } from "./lider-turma.service.js";
export { reuniaoDemocraticaService } from "./reuniao-democratica.service.js";
// Exportadores oficiais
export { exportacaoEducacensoService } from "./exportacao-educacenso.service.js";
export { exportacaoPresencaService } from "./exportacao-presenca.service.js";
