export { authService } from "./auth.service.js";
export { serieService } from "./serie.service.js";
export { nivelEnsinoService } from "./nivel-ensino.service.js";
export { etapaService } from "./etapa.service.js";
export { tipoEducacaoService } from "./tipo-educacao.service.js";
export { escolaService } from "./escola.service.js";
export { turmaService } from "./turma.service.js";
export { matriculaService } from "./matricula.service.js";
export { profissionalService } from "./profissional.service.js";
export { moduleService } from "./module.service.js";
export { phaseService } from "./phase.service.js";
export { calendarioService } from "./calendario.service.js";
// Módulo 2 — Gestão Pedagógica
export { frequenciaService } from "./frequencia.service.js";
export { notaService } from "./nota.service.js";
export { avaliacaoService } from "./avaliacao.service.js";
export { disciplinaService } from "./disciplina.service.js";
export { configuracaoAvaliacaoService } from "./configuracao-avaliacao.service.js";
export { gradeHorariaService } from "./grade-horaria.service.js";
