-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_matriculas" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "numeroMatricula" TEXT NOT NULL,
    "anoLetivo" INTEGER NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'ATIVA',
    "dataMatricula" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "nomeAluno" TEXT NOT NULL,
    "dataNascimento" DATETIME NOT NULL,
    "cpfAluno" TEXT,
    "rgAluno" TEXT,
    "sexo" TEXT NOT NULL,
    "naturalidade" TEXT,
    "nacionalidade" TEXT NOT NULL DEFAULT 'Brasileira',
    "corRaca" TEXT,
    "possuiDeficiencia" BOOLEAN NOT NULL DEFAULT false,
    "tipoDeficiencia" TEXT,
    "nomeResponsavel" TEXT NOT NULL,
    "cpfResponsavel" TEXT,
    "telefoneResponsavel" TEXT,
    "emailResponsavel" TEXT,
    "parentesco" TEXT,
    "endereco" TEXT,
    "bairro" TEXT,
    "cidade" TEXT,
    "estado" TEXT,
    "cep" TEXT,
    "documentosEntregues" TEXT,
    "observacoes" TEXT,
    "fotoAluno" TEXT,
    "documentoRG" TEXT,
    "documentoCPF" TEXT,
    "comprovanteResidencia" TEXT,
    "certidaoNascimento" TEXT,
    "historicoEscolar" TEXT,
    "outrosDocumentos" TEXT,
    "tipoSanguineo" TEXT,
    "alergias" TEXT,
    "medicamentos" TEXT,
    "condicoesSaude" TEXT,
    "planoSaude" TEXT,
    "numeroCartaoSUS" TEXT,
    "contatoEmergenciaNome" TEXT,
    "contatoEmergenciaTelefone" TEXT,
    "contatoEmergenciaParentesco" TEXT,
    "autorizacaoImagem" BOOLEAN NOT NULL DEFAULT false,
    "autorizacaoSaida" BOOLEAN NOT NULL DEFAULT false,
    "pessoasAutorizadasRetirar" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "escolaId" TEXT NOT NULL,
    "etapaId" TEXT NOT NULL,
    "turmaId" TEXT,
    CONSTRAINT "matriculas_escolaId_fkey" FOREIGN KEY ("escolaId") REFERENCES "escolas" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "matriculas_etapaId_fkey" FOREIGN KEY ("etapaId") REFERENCES "etapas_ensino" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "matriculas_turmaId_fkey" FOREIGN KEY ("turmaId") REFERENCES "turmas" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_matriculas" ("anoLetivo", "bairro", "cep", "certidaoNascimento", "cidade", "comprovanteResidencia", "corRaca", "cpfAluno", "cpfResponsavel", "createdAt", "dataMatricula", "dataNascimento", "documentoCPF", "documentoRG", "documentosEntregues", "emailResponsavel", "endereco", "escolaId", "estado", "etapaId", "fotoAluno", "historicoEscolar", "id", "nacionalidade", "naturalidade", "nomeAluno", "nomeResponsavel", "numeroMatricula", "observacoes", "outrosDocumentos", "parentesco", "possuiDeficiencia", "rgAluno", "sexo", "status", "telefoneResponsavel", "tipoDeficiencia", "turmaId", "updatedAt") SELECT "anoLetivo", "bairro", "cep", "certidaoNascimento", "cidade", "comprovanteResidencia", "corRaca", "cpfAluno", "cpfResponsavel", "createdAt", "dataMatricula", "dataNascimento", "documentoCPF", "documentoRG", "documentosEntregues", "emailResponsavel", "endereco", "escolaId", "estado", "etapaId", "fotoAluno", "historicoEscolar", "id", "nacionalidade", "naturalidade", "nomeAluno", "nomeResponsavel", "numeroMatricula", "observacoes", "outrosDocumentos", "parentesco", "possuiDeficiencia", "rgAluno", "sexo", "status", "telefoneResponsavel", "tipoDeficiencia", "turmaId", "updatedAt" FROM "matriculas";
DROP TABLE "matriculas";
ALTER TABLE "new_matriculas" RENAME TO "matriculas";
CREATE UNIQUE INDEX "matriculas_numeroMatricula_key" ON "matriculas"("numeroMatricula");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
