export const alunoForm = {
  censoAluno2025: {
    identificacao: {
      identificacaoUnica: "",
      codigoEscola: "",
      cpf: "",
      nomeCompleto: "",
      dataNascimento: "",
      filiacao: {
        filiacao1: "",
        filiacao2: "",
      },
      sexo: "",
      corRaca: "",
      povoIndigena: {
        codigo: "",
        observacao: "Ver código no Caderno de Conceitos e Orientações",
      },
      nacionalidade: "",
      paisNacionalidade: "",
      naturalidade: {
        ufNascimento: "",
        municipioNascimento: "",
      },
    },
    deficienciasTranstornos: {
      deficiencia: {
        possui: false,
        tipos: [],
        opcoesTipos: [
          "Cegueira",
          "Baixa visão",
          "Visão monocular",
          "Surdez",
          "Deficiência auditiva",
          "Surdocegueira",
          "Deficiência física",
          "Deficiência intelectual",
          "Deficiência múltipla",
          "Transtorno do espectro autista",
          "Altas habilidades ou superdotação",
        ],
      },
      transtornosAprendizagem: {
        possui: false,
        tipos: [],
        opcoesTipos: [
          "Dislexia",
          "Discalculia ou outro transtorno da matemática e raciocínio lógico",
          "Disgrafia, Disortografia ou outro transtorno da escrita e comunicação",
          "Dislalia ou outro transtorno da linguagem e comunicação",
          "Transtorno do Déficit de Atenção com Hiperatividade (TDAH)",
          "Transtorno do Processamento Auditivo Central (TPAC)",
        ],
      },
      recursosAcessibilidade: {
        necessita: false,
        recursos: [],
        opcoesRecursos: [
          "Auxílio ledor",
          "Auxílio transcrição",
          "Guia-intérprete",
          "Tradutor-intérprete de Libras",
          "Leitura labial",
          "Prova em Braille",
          "Prova superampliada (Fonte 24)",
          "Prova ampliada (Fonte 18)",
          "Prova em Vídeo Libras",
          "CD com áudio para deficiente visual",
          "Material didático em Braille",
          "Prova de Língua Portuguesa como Segunda Língua para surdos e deficientes auditivos",
        ],
      },
    },
    documento: {
      numeroMatriculaCertidao: "",
      observacao: "Certidão de nascimento nova",
    },
    areaResidencial: {
      paisResidencia: "",
      cep: "",
      uf: "",
      municipio: "",
      localizacao: "",
      localizacaoDiferenciada: "",
      opcoesLocalizacao: ["Urbana", "Rural"],
      opcoesLocalizacaoDiferenciada: [
        "Não está em área de localização diferenciada",
        "Área de assentamento",
        "Terra indígena",
        "Comunidade quilombola",
        "Área onde se localizam povos e comunidades tradicionais",
      ],
    },
    vinculo: {
      nomeTurma: "",
      etapaAlunoTurma: "",
      opcoesEtapa: [
        "Creche",
        "Pré-escola",
        "Ensino fundamental",
        "EJA - Anos iniciais",
        "EJA - Anos finais",
        "Curso técnico - Concomitante",
        "Curso técnico - Subsequente",
      ],
      atendimentoEducacionalEspecializado: {
        tipos: [],
        opcoesTipos: [
          "Ensino do Sistema Braille",
          "Ensino das técnicas de cálculo no Soroban",
          "Ensino de técnicas para orientação e mobilidade",
          "Ensino da Língua Brasileira de Sinais (Libras)",
          "Ensino da Língua Portuguesa como Segunda Língua",
          "Ensino do uso da Comunicação Alternativa e Aumentativa (CAA)",
          "Ensino da informática acessível",
          "Ensino do uso de recursos ópticos e não ópticos",
          "Desenvolvimento de funções cognitivas",
          "Desenvolvimento de vida autônoma",
          "Enriquecimento curricular",
        ],
      },
      escolarizacaoOutroEspaco: "",
      opcoesEscolarizacaoOutro: [
        "Não recebe escolarização fora da escola",
        "Em domicílio",
        "Em hospital",
      ],
      transporteEscolar: {
        utiliza: false,
        poderPublico: "",
        opcoesPoderPublico: ["Municipal", "Estadual"],
        tiposVeiculo: [],
        opcoesTiposVeiculo: {
          rodoviario: [
            "Bicicleta",
            "Tração animal",
            "Outro tipo de veículo rodoviário",
            "Vans/Kombis",
            "Micro-ônibus",
            "Ônibus",
          ],
          aquaviario: [
            "Embarcação - capacidade de até 5 alunos",
            "Embarcação - capacidade entre 5 a 15 alunos",
            "Embarcação - capacidade entre 15 a 35 alunos",
            "Embarcação - capacidade acima de 35 alunos",
          ],
        },
      },
    },
    metadados: {
      dataPreenchimento: "",
      versaoFormulario: "2025-preliminar",
      observacoes: {
        cpf: "Dados carregados da base da Receita Federal",
        povoIndigena: "Ver código no Caderno de Conceitos e Orientações",
        certidao: "Número da matrícula da certidão nova",
        recursos:
          "Para uso em sala de aula e participação em avaliações do Inep (Saeb)",
      },
    },
    opcoesSexo: ["Masculino", "Feminino"],
    opcoesCorRaca: [
      "Branca",
      "Preta",
      "Parda",
      "Amarela",
      "Indígena",
      "Não declarada",
    ],
    opcoesNacionalidade: [
      "Brasileira",
      "Brasileira – nascido no exterior ou naturalizado",
      "Estrangeira",
    ],
  },
};
