export const escolaForm = {
  censoEscolar2025: {
    identificacao: {
      codigoEscola: "",
      nomeEscola: "",
      dependenciaAdministrativa: "",
      localizacao: "",
    },
    vinculacaoInstitucional: {
      orgaoVinculacao: "",
      orgaoRegional: "",
      regulamentacao: "",
      esferaRegulamentacao: [],
      entidadeSuperior: [],
      parceriaConvenio: {
        possui: "",
        poderPublico: "",
        formaContratacaoEstadual: [],
        formaContratacaoMunicipal: [],
      },
    },
    funcionamento: {
      situacao: "",
      anoLetivo: {
        inicio: "",
        termino: "",
      },
    },
    endereco: {
      cep: "",
      uf: "",
      municipio: "",
      regiaoAdministrativa: "",
      distrito: "",
      logradouro: "",
      numero: "",
      complemento: "",
      bairro: "",
      ddd: "",
      telefone: "",
      outroTelefone: "",
      email: "",
      localizacaoGeografica: "",
      localizacaoDiferenciada: "",
    },
    vinculacaoInstitucionalIES: {
      unidadeVinculada: "",
      codigoEscolaSede: "",
      codigoIES: "",
    },
    escolaPrivada: {
      categoria: "",
      mantenedora: [],
      cnpjMantenedora: "",
      cnpjEscola: "",
    },
    estruturaFisica: {
      localFuncionamento: "",
      formaOcupacao: "",
      compartilhaPredio: "",
      codigoEscolaCompartilhada: "",
      infraestruturaServicosBasicos: {
        aguaPotavel: "",
        abastecimentoAgua: [],
        fonteEnergia: [],
        esgotamento: [],
        destinacaoLixo: [],
        tratamentoLixo: [],
      },
      dependenciasFisicas: {
        administracao: {
          salaDiretoria: false,
          salaProfessores: false,
          salaSecretaria: false,
          almoxarifado: false,
        },
        alimentacao: {
          cozinha: false,
          refeitorio: false,
          despensa: false,
        },
        banheiros: {
          banheiro: false,
          banheiroAcessivel: false,
          banheiroFuncionarios: false,
          banheiroEducacaoInfantil: false,
          vestiarioChuveiro: false,
        },
        acomodacao: {
          dormitorioAluno: false,
          dormitorioProfessor: false,
          salaRepouso: false,
        },
        aprendizagem: {
          biblioteca: false,
          salaLeitura: false,
          laboratorioInformatica: false,
          laboratorioCiencias: false,
          laboratorioEducacaoProfissional: false,
          salaOficinaEducacaoProfissional: false,
          salaRecursosMultifuncionais: false,
          auditorio: false,
          salaMultiuso: false,
          salaMusica: false,
          salaDanca: false,
          salaArtes: false,
          estudioGravacao: false,
        },
        esportesRecreacao: {
          quadraCoberta: false,
          quadraDescoberta: false,
          piscina: false,
          patioCoberto: false,
          patioDescoberto: false,
          parqueInfantil: false,
          terreirao: false,
          areaVegetacao: false,
        },
        meioAmbiente: {
          areaHorta: false,
          viveiro: false,
        },
      },
      recursosAcessibilidade: [],
      salas: {
        dentroPredioCivil: 0,
        foraPredioCivil: 0,
        climatizadas: 0,
        comAcessibilidade: 0,
        comCantinoLeitura: 0,
      },
    },
    equipamentosTecnologicos: {
      equipamentosAdministrativos: [],
      equipamentosEnsinoAprendizagem: [],
      computadores: {
        desktop: 0,
        portateis: 0,
        tablets: 0,
      },
      redeLocal: [],
      internet: {
        acessoInternet: [],
        dispositivosAcesso: [],
        bandaLarga: "",
      },
    },
    recursosHumanos: {
      secretarioEscolar: 0,
      auxiliaresSecretaria: 0,
      auxiliarServicosGerais: 0,
      bibliotecario: 0,
      apoioPedagogico: 0,
      seguranca: 0,
      tecnicosLaboratorio: 0,
      psicologo: 0,
      fonoaudiologo: 0,
      profissionaisAlimentacao: 0,
      coordenadorTurno: 0,
      nutricionista: 0,
      orientadorComunitario: 0,
      viceDiretor: 0,
      tradutorLibras: 0,
      agronomos: 0,
      revisorBraille: 0,
      bombeiroBrigadista: 0,
    },
    organizacaoEscolar: {
      alimentacaoEscolar: "",
      escolaIndigena: {
        eh: "",
        linguaEnsino: [],
        codigoLinguaIndigena: ["", "", ""],
      },
      instrumentosMateriais: [],
      educacaoAmbiental: {
        desenvolve: "",
        formas: [],
      },
      gestao: {
        pppAtualizado: "",
        orgaosColegiados: [],
        compartilhaEspacos: "",
        usaEspacosEntorno: "",
        siteBlogRedes: "",
      },
      acesso: {
        exameSelecao: "",
        sistemaCotas: "",
        reservaVagas: [],
      },
    },
  },
};
